# Pre-Processing and Cleaning of Data

In [1]:
import polars as pl
from pathlib import Path

# Load Raw Data from Public CSVs

In [ ]:
dir_path = Path().cwd().parent.parent
if (dir_path / Path('data/raw_data')).exists():
    raw_data_path = dir_path / Path('data/raw_data')
else:
    (dir_path / Path('data/raw_data')).mkdir(parents=True, exist_ok=True)
    raw_data_path = dir_path / Path('data/raw_data')

In [3]:
crash_data_path = dir_path / raw_data_path /  Path("Motor_Vehicle_Collisions_-_Crashes.csv")
if crash_data_path.exists():
    crash_data = pl.read_csv(str(crash_data_path), low_memory=False)
else:
    raise FileNotFoundError("Please download dataset and rename appropiately: https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95/about_data")

person_data_path = dir_path / raw_data_path / Path("Motor_Vehicle_Collisions_-_Person.csv")
if person_data_path.exists():
    person_data = pl.read_csv(str(person_data_path), low_memory=False)
else:
    raise FileNotFoundError("Please download dataset and rename appropiately: https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Person/f55k-p6yu/about_data")

# Perform EDA to Learn about data. Starting with Crash Data

In [4]:
print("Crash Data:")
display(crash_data.head())

Crash Data:

shape: (5, 29)
┌────────────┬───────┬──────────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ CRASH DATE ┆ CRASH ┆ BOROUGH  ┆ ZIP CODE ┆ … ┆ VEHICLE    ┆ VEHICLE    ┆ VEHICLE    ┆ VEHICLE    │
│ ---        ┆ TIME  ┆ ---      ┆ ---      ┆   ┆ TYPE CODE  ┆ TYPE CODE  ┆ TYPE CODE  ┆ TYPE CODE  │
│ str        ┆ ---   ┆ str      ┆ i64      ┆   ┆ 2          ┆ 3          ┆ 4          ┆ 5          │
│            ┆ str   ┆          ┆          ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆       ┆          ┆          ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
╞════════════╪═══════╪══════════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 09/11/2021 ┆ 2:39  ┆ null     ┆ null     ┆ … ┆ Sedan      ┆ null       ┆ null       ┆ null       │
│ 03/26/2022 ┆ 11:45 ┆ null     ┆ null     ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 06/29/2022 ┆ 6:55  ┆ null     ┆ null     ┆ … ┆ Pick-up    ┆ null       ┆ null       ┆ null       │
│            ┆       ┆          ┆          ┆   ┆ Truck      ┆            ┆            ┆            │
│ 09/11/2021 ┆ 9:35  ┆ BROOKLYN ┆ 11208    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 12/14/2021 ┆ 8:13  ┆ BROOKLYN ┆ 11233    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
└────────────┴───────┴──────────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [5]:
# display datatypes and range
print("\nCrash Data Info:")
crash_data.describe()

Crash Data Info:

shape: (9, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ CRASH     ┆ CRASH     ┆ BOROUGH   ┆ … ┆ VEHICLE   ┆ VEHICLE   ┆ VEHICLE   ┆ VEHICLE  │
│ ---       ┆ DATE      ┆ TIME      ┆ ---       ┆   ┆ TYPE CODE ┆ TYPE CODE ┆ TYPE CODE ┆ TYPE     │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ 2         ┆ 3         ┆ 4         ┆ CODE 5   │
│           ┆ str       ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2125763   ┆ 2125763   ┆ 1464659   ┆ … ┆ 1712729   ┆ 147095    ┆ 33459     ┆ 9148     │
│ null_coun ┆ 0         ┆ 0         ┆ 661104    ┆ … ┆ 413034    ┆ 1978668   ┆ 2092304   ┆ 2116615  │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ min       ┆ 01/01/201 ┆ 0:00      ┆ BRONX     ┆ … ┆ (ceme     ┆ 2 dr      ┆ 2 dr      ┆ 2 dr     │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆ sedan     ┆ sedan     ┆ sedan    │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ 12/31/202 ┆ 9:59      ┆ STATEN    ┆ … ┆ yw        ┆ yello     ┆ van       ┆ van      │
│           ┆ 3         ┆           ┆ ISLAND    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
crash_data = crash_data.rename(
    {col: col.replace("_", " ") for col in crash_data.columns}
)

crash_data.columns

['CRASH DATE',
 'CRASH TIME',
 'BOROUGH',
 'ZIP CODE',
 'LATITUDE',
 'LONGITUDE',
 'LOCATION',
 'ON STREET NAME',
 'CROSS STREET NAME',
 'OFF STREET NAME',
 'NUMBER OF PERSONS INJURED',
 'NUMBER OF PERSONS KILLED',
 'NUMBER OF PEDESTRIANS INJURED',
 'NUMBER OF PEDESTRIANS KILLED',
 'NUMBER OF CYCLIST INJURED',
 'NUMBER OF CYCLIST KILLED',
 'NUMBER OF MOTORIST INJURED',
 'NUMBER OF MOTORIST KILLED',
 'CONTRIBUTING FACTOR VEHICLE 1',
 'CONTRIBUTING FACTOR VEHICLE 2',
 'CONTRIBUTING FACTOR VEHICLE 3',
 'CONTRIBUTING FACTOR VEHICLE 4',
 'CONTRIBUTING FACTOR VEHICLE 5',
 'COLLISION ID',
 'VEHICLE TYPE CODE 1',
 'VEHICLE TYPE CODE 2',
 'VEHICLE TYPE CODE 3',
 'VEHICLE TYPE CODE 4',
 'VEHICLE TYPE CODE 5']

### Cleaning the Location related Columns

In [7]:
# Sub-setting the crash DataFrame for only the columns I need
location_df = crash_data[['COLLISION ID', 'CRASH DATE', 'CRASH TIME', 'LATITUDE',
       'LONGITUDE', 'LOCATION', 'NUMBER OF PERSONS INJURED',
       'NUMBER OF PERSONS KILLED', 'CONTRIBUTING FACTOR VEHICLE 1',
       'CONTRIBUTING FACTOR VEHICLE 2']]

In [8]:
display(location_df.describe())

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ COLLISION ┆ CRASH     ┆ CRASH     ┆ … ┆ NUMBER OF ┆ NUMBER OF ┆ CONTRIBUT ┆ CONTRIBU │
│ ---       ┆ ID        ┆ DATE      ┆ TIME      ┆   ┆ PERSONS   ┆ PERSONS   ┆ ING       ┆ TING     │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ INJURED   ┆ KILLED    ┆ FACTOR    ┆ FACTOR   │
│           ┆ f64       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ VEHICLE 1 ┆ VEHICLE  │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ 2        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2.125763e ┆ 2125763   ┆ 2125763   ┆ … ┆ 2.125745e ┆ 2.125732e ┆ 2118619   ┆ 1792690  │
│           ┆ 6         ┆           ┆           ┆   ┆ 6         ┆ 6         ┆           ┆          │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 18.0      ┆ 31.0      ┆ 7144      ┆ 333073   │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 3.1970e6  ┆ null      ┆ null      ┆ … ┆ 0.316802  ┆ 0.001528  ┆ null      ┆ null     │
│ std       ┆ 1.5064e6  ┆ null      ┆ null      ┆ … ┆ 0.706167  ┆ 0.041278  ┆ null      ┆ null     │
│ min       ┆ 22.0      ┆ 01/01/201 ┆ 0:00      ┆ … ┆ 0.0       ┆ 0.0       ┆ 1         ┆ 1        │
│           ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 3.167561e ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 3.699141e ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 4.230816e ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 4.762597e ┆ 12/31/202 ┆ 9:59      ┆ … ┆ 43.0      ┆ 8.0       ┆ Windshiel ┆ Windshie │
│           ┆ 6         ┆ 3         ┆           ┆   ┆           ┆           ┆ d Inadequ ┆ ld Inade │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ate       ┆ quate    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
# Check for missing values 
print("Missing values in Location Data:")
print(location_df.null_count())

Missing values in Location Data:
shape: (1, 10)
┌─────────────┬───────┬───────┬──────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ COLLISION   ┆ CRASH ┆ CRASH ┆ LATITUDE ┆ … ┆ NUMBER OF   ┆ NUMBER OF   ┆ CONTRIBUTI ┆ CONTRIBUTI │
│ ID          ┆ DATE  ┆ TIME  ┆ ---      ┆   ┆ PERSONS     ┆ PERSONS     ┆ NG FACTOR  ┆ NG FACTOR  │
│ ---         ┆ ---   ┆ ---   ┆ u32      ┆   ┆ INJURED     ┆ KILLED      ┆ VEHICLE 1  ┆ VEHICLE 2  │
│ u32         ┆ u32   ┆ u32   ┆          ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆       ┆       ┆          ┆   ┆ u32         ┆ u32         ┆ u32        ┆ u32        │
╞═════════════╪═══════╪═══════╪══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 0           ┆ 0     ┆ 0     ┆ 252597   ┆ … ┆ 18          ┆ 31          ┆ 7144       ┆ 333073     │
└─────────────┴───────┴───────┴──────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# Drop all the rows where location is missing
location_df = location_df.drop_nulls(subset=['LOCATION'])

location_df = location_df.filter(
    (pl.col("LATITUDE").is_between(40.5774, 45.01585))  &
        (pl.col("LONGITUDE").is_between(-74.2591, -73.7004))
)
location_df = location_df.drop("LOCATION")

In [11]:
# Cleaning of Contributing Factors

rename_dict ={
    'Cell Phone (hand-held)': 'Cell Phone (Hand-Held)',
    'Cell Phone (hand-Held)': 'Cell Phone (Hand-Held)',
    'Cell Phone (hands-free)': 'Cell Phone (Hands-Free)',
    'Drugs (illegal)': 'Drugs (Illegal)', 
    'Illnes': 'Illness'
}

location_df = location_df.drop_nulls(
    subset=["CONTRIBUTING FACTOR VEHICLE 1", "CONTRIBUTING FACTOR VEHICLE 2"]
    ).filter(
        (
            (pl.col("CONTRIBUTING FACTOR VEHICLE 1") != "Unspecified") |
            (pl.col("CONTRIBUTING FACTOR VEHICLE 2") != "Unspecified")
        )
        &
        (pl.col("CONTRIBUTING FACTOR VEHICLE 1") != "80")
        &
        (pl.col("CONTRIBUTING FACTOR VEHICLE 2") != "80")
        &
        (pl.col("CONTRIBUTING FACTOR VEHICLE 1") != "1")
        &
        (pl.col("CONTRIBUTING FACTOR VEHICLE 2") != "1")
    ).with_columns(
        pl.col("CONTRIBUTING FACTOR VEHICLE 1").replace(rename_dict),
        pl.col("CONTRIBUTING FACTOR VEHICLE 2").replace(rename_dict),
    )

In [12]:
# fill nulls with 'UNKNOWN' or 0 

location_df = location_df.with_columns(
    pl.col("NUMBER OF PERSONS INJURED").fill_null(0.0),
    pl.col("NUMBER OF PERSONS KILLED").fill_null(0.0)
)

print("Location Data after cleaning:")
print(location_df.null_count())

Location Data after cleaning:
shape: (1, 9)
┌─────────────┬───────┬───────┬──────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ COLLISION   ┆ CRASH ┆ CRASH ┆ LATITUDE ┆ … ┆ NUMBER OF   ┆ NUMBER OF   ┆ CONTRIBUTI ┆ CONTRIBUTI │
│ ID          ┆ DATE  ┆ TIME  ┆ ---      ┆   ┆ PERSONS     ┆ PERSONS     ┆ NG FACTOR  ┆ NG FACTOR  │
│ ---         ┆ ---   ┆ ---   ┆ u32      ┆   ┆ INJURED     ┆ KILLED      ┆ VEHICLE 1  ┆ VEHICLE 2  │
│ u32         ┆ u32   ┆ u32   ┆          ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆       ┆       ┆          ┆   ┆ u32         ┆ u32         ┆ u32        ┆ u32        │
╞═════════════╪═══════╪═══════╪══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 0           ┆ 0     ┆ 0     ┆ 0        ┆ … ┆ 0           ┆ 0           ┆ 0          ┆ 0          │
└─────────────┴───────┴───────┴──────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [13]:
location_df.head()

shape: (5, 9)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ COLLISION  ┆ CRASH DATE ┆ CRASH ┆ LATITUDE   ┆ … ┆ NUMBER OF ┆ NUMBER OF ┆ CONTRIBUT ┆ CONTRIBUT │
│ ID         ┆ ---        ┆ TIME  ┆ ---        ┆   ┆ PERSONS   ┆ PERSONS   ┆ ING       ┆ ING       │
│ ---        ┆ str        ┆ ---   ┆ f64        ┆   ┆ INJURED   ┆ KILLED    ┆ FACTOR    ┆ FACTOR    │
│ i64        ┆            ┆ str   ┆            ┆   ┆ ---       ┆ ---       ┆ VEHICLE 1 ┆ VEHICLE 2 │
│            ┆            ┆       ┆            ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---       │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ str       ┆ str       │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 4486555    ┆ 12/14/2021 ┆ 17:05 ┆ 40.709183  ┆ … ┆ 0.0       ┆ 0.0       ┆ Passing   ┆ Unspecifi │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ Too       ┆ ed        │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ Closely   ┆           │
│ 4487074    ┆ 12/14/2021 ┆ 21:10 ┆ 40.67172   ┆ … ┆ 0.0       ┆ 0.0       ┆ Driver    ┆ Unspecifi │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ Inexperie ┆ ed        │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ nce       ┆           │
│ 4486519    ┆ 12/14/2021 ┆ 14:58 ┆ 40.75144   ┆ … ┆ 0.0       ┆ 0.0       ┆ Passing   ┆ Unspecifi │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ Too       ┆ ed        │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ Closely   ┆           │
│ 4486934    ┆ 12/13/2021 ┆ 0:34  ┆ 40.701275  ┆ … ┆ 0.0       ┆ 0.0       ┆ Passing   ┆ Unspecifi │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ or Lane   ┆ ed        │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ Usage     ┆           │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ Improper  ┆           │
│ 4487127    ┆ 12/14/2021 ┆ 16:50 ┆ 40.675884  ┆ … ┆ 0.0       ┆ 0.0       ┆ Turning   ┆ Unspecifi │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ Improperl ┆ ed        │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ y         ┆           │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
import datetime as dt
# Handle Types

location_df = location_df.with_columns(
    pl.col("CRASH DATE").str.strptime(pl.Date, format="%m/%d/%Y", strict=False),
    
    # Convert CRASH_TIME to time (as HH:MM)
    pl.col("CRASH TIME").str.strptime(pl.Time, format="%H:%M", strict=False),
    
    # Convert numeric columns to integer
    pl.col("NUMBER OF PERSONS INJURED").cast(pl.Int32),
    pl.col("NUMBER OF PERSONS KILLED").cast(pl.Int32),
)

location_df.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ COLLISION ┆ CRASH     ┆ CRASH     ┆ LATITUDE  ┆ … ┆ NUMBER OF ┆ NUMBER OF ┆ CONTRIBUT ┆ CONTRIBU │
│ ID        ┆ DATE      ┆ TIME      ┆ ---       ┆   ┆ PERSONS   ┆ PERSONS   ┆ ING       ┆ TING     │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ INJURED   ┆ KILLED    ┆ FACTOR    ┆ FACTOR   │
│ i64       ┆ date      ┆ time      ┆           ┆   ┆ ---       ┆ ---       ┆ VEHICLE 1 ┆ VEHICLE  │
│           ┆           ┆           ┆           ┆   ┆ i32       ┆ i32       ┆ ---       ┆ 2        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4486555   ┆ 2021-12-1 ┆ 17:05:00  ┆ 40.709183 ┆ … ┆ 0         ┆ 0         ┆ Passing   ┆ Unspecif │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ Too       ┆ ied      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Closely   ┆          │
│ 4487074   ┆ 2021-12-1 ┆ 21:10:00  ┆ 40.67172  ┆ … ┆ 0         ┆ 0         ┆ Driver    ┆ Unspecif │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ Inexperie ┆ ied      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nce       ┆          │
│ 4486519   ┆ 2021-12-1 ┆ 14:58:00  ┆ 40.75144  ┆ … ┆ 0         ┆ 0         ┆ Passing   ┆ Unspecif │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ Too       ┆ ied      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Closely   ┆          │
│ 4486934   ┆ 2021-12-1 ┆ 00:34:00  ┆ 40.701275 ┆ … ┆ 0         ┆ 0         ┆ Passing   ┆ Unspecif │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆ or Lane   ┆ ied      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Usage     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Improper  ┆          │
│ 4487127   ┆ 2021-12-1 ┆ 16:50:00  ┆ 40.675884 ┆ … ┆ 0         ┆ 0         ┆ Turning   ┆ Unspecif │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ Improperl ┆ ied      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ y         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
# Creating Encoding Data
location_df = location_df.with_columns(
    pl.when(pl.col("NUMBER OF PERSONS KILLED") > 0)
      .then(pl.lit("Fatal"))
      .when(pl.col("NUMBER OF PERSONS INJURED") >= 3)
      .then(pl.lit("Major Injury"))
      .when(pl.col("NUMBER OF PERSONS INJURED") > 0)
      .then(pl.lit("Minor Injury"))
      .otherwise(pl.lit("No Injury"))
      .alias("ACCIDENT SEVERITY")
)

print(location_df.head())

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ COLLISION ┆ CRASH     ┆ CRASH     ┆ LATITUDE  ┆ … ┆ NUMBER OF ┆ CONTRIBUT ┆ CONTRIBUT ┆ ACCIDENT │
│ ID        ┆ DATE      ┆ TIME      ┆ ---       ┆   ┆ PERSONS   ┆ ING       ┆ ING       ┆ SEVERITY │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ KILLED    ┆ FACTOR    ┆ FACTOR    ┆ ---      │
│ i64       ┆ date      ┆ time      ┆           ┆   ┆ ---       ┆ VEHICLE 1 ┆ VEHICLE 2 ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ i32       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4486555   ┆ 2021-12-1 ┆ 17:05:00  ┆ 40.709183 ┆ … ┆ 0         ┆ Passing   ┆ Unspecifi ┆ No       │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆ Too       ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ Closely   ┆           ┆          │
│ 4487074   ┆ 2021-12-1 ┆ 21:10:00  ┆ 40.67172  ┆ … ┆ 0         ┆ Driver    ┆ Unspecifi ┆ No       │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆ Inexperie ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ nce       ┆           ┆          │
│ 4486519   ┆ 2021-12-1 ┆ 14:58:00  ┆ 40.75144  ┆ … ┆ 0         ┆ Passing   ┆ Unspecifi ┆ No       │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆ Too       ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ Closely   ┆           ┆          │
│ 4486934   ┆ 2021-12-1 ┆ 00:34:00  ┆ 40.701275 ┆ … ┆ 0         ┆ Passing   ┆ Unspecifi ┆ No       │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆ or Lane   ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ Usage     ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Improper  ┆           ┆          │
│ 4487127   ┆ 2021-12-1 ┆ 16:50:00  ┆ 40.675884 ┆ … ┆ 0         ┆ Turning   ┆ Unspecifi ┆ No       │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆ Improperl ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ y         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
location_df.head()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ COLLISION ┆ CRASH     ┆ CRASH     ┆ LATITUDE  ┆ … ┆ NUMBER OF ┆ CONTRIBUT ┆ CONTRIBUT ┆ ACCIDENT │
│ ID        ┆ DATE      ┆ TIME      ┆ ---       ┆   ┆ PERSONS   ┆ ING       ┆ ING       ┆ SEVERITY │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ KILLED    ┆ FACTOR    ┆ FACTOR    ┆ ---      │
│ i64       ┆ date      ┆ time      ┆           ┆   ┆ ---       ┆ VEHICLE 1 ┆ VEHICLE 2 ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ i32       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4486555   ┆ 2021-12-1 ┆ 17:05:00  ┆ 40.709183 ┆ … ┆ 0         ┆ Passing   ┆ Unspecifi ┆ No       │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆ Too       ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ Closely   ┆           ┆          │
│ 4487074   ┆ 2021-12-1 ┆ 21:10:00  ┆ 40.67172  ┆ … ┆ 0         ┆ Driver    ┆ Unspecifi ┆ No       │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆ Inexperie ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ nce       ┆           ┆          │
│ 4486519   ┆ 2021-12-1 ┆ 14:58:00  ┆ 40.75144  ┆ … ┆ 0         ┆ Passing   ┆ Unspecifi ┆ No       │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆ Too       ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ Closely   ┆           ┆          │
│ 4486934   ┆ 2021-12-1 ┆ 00:34:00  ┆ 40.701275 ┆ … ┆ 0         ┆ Passing   ┆ Unspecifi ┆ No       │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆ or Lane   ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ Usage     ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Improper  ┆           ┆          │
│ 4487127   ┆ 2021-12-1 ┆ 16:50:00  ┆ 40.675884 ┆ … ┆ 0         ┆ Turning   ┆ Unspecifi ┆ No       │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆ Improperl ┆ ed        ┆ Injury   │
│           ┆           ┆           ┆           ┆   ┆           ┆ y         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Attempt to tie Locations (LAT and LONG) to Boroughs

In [17]:
# Try to find the Borough for each location entry
import geopandas as gpd

points_df = location_df.to_pandas()

points_gdf = gpd.GeoDataFrame(
    points_df,
    geometry=gpd.points_from_xy(
        points_df["LONGITUDE"],
        points_df["LATITUDE"]
    ),
    crs="EPSG:4326"
)

# Load the shapefile of boroughs (assuming it contains a 'BOROUGH' column)
shapefile_path = dir_path.parent  / Path('Borough Boundaries/geo_borough.shp')
boroughs_gdf = gpd.read_file(shapefile_path)

if boroughs_gdf.crs is None:
    boroughs_gdf.set_crs(epsg=2263, inplace=True)

# Ensure the shapefile uses the same CRS as the points
boroughs_gdf = boroughs_gdf.to_crs(epsg=4326)
# Perform a spatial join to find which borough each point is in
result_gdf = gpd.sjoin(points_gdf, boroughs_gdf, how='inner', predicate='within')

result_gdf.head()

,COLLISION ID,CRASH DATE,CRASH TIME,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,ACCIDENT SEVERITY,geometry,index_right,boro_code,boro_name,shape_area,shape_leng
0,4486555,2021-12-14,17:05:00,40.709183,-73.956825,0,0,Passing Too Closely,Unspecified,No Injury,POINT (-73.95682 40.70918),0,3.0,Brooklyn,1.934143e+09,728147.130565
1,4487074,2021-12-14,21:10:00,40.671720,-73.897100,0,0,Driver Inexperience,Unspecified,No Injury,POINT (-73.8971 40.67172),0,3.0,Brooklyn,1.934143e+09,728147.130565
2,4486519,2021-12-14,14:58:00,40.751440,-73.973970,0,0,Passing Too Closely,Unspecified,No Injury,POINT (-73.97397 40.75144),2,1.0,Manhattan,6.366461e+08,360037.525777
3,4486934,2021-12-13,00:34:00,40.701275,-73.888870,0,0,Passing or Lane Usage Improper,Unspecified,No Injury,POINT (-73.88887 40.70128),4,4.0,Queens,3.041418e+09,888197.010944
4,4487127,2021-12-14,16:50:00,40.675884,-73.755770,0,0,Turning Improperly,Unspecified,No Injury,POINT (-73.75577 40.67588),4,4.0,Queens,3.041418e+09,888197.010944

In [18]:
location_df = result_gdf.drop(columns=['boro_code', 'shape_area', 'shape_leng', 'geometry', 'index_right'])
location_df.rename(columns={'boro_name': 'BOROUGH'}, inplace=True)
location_df.head()

,COLLISION ID,CRASH DATE,CRASH TIME,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,ACCIDENT SEVERITY,BOROUGH
0,4486555,2021-12-14,17:05:00,40.709183,-73.956825,0,0,Passing Too Closely,Unspecified,No Injury,Brooklyn
1,4487074,2021-12-14,21:10:00,40.671720,-73.897100,0,0,Driver Inexperience,Unspecified,No Injury,Brooklyn
2,4486519,2021-12-14,14:58:00,40.751440,-73.973970,0,0,Passing Too Closely,Unspecified,No Injury,Manhattan
3,4486934,2021-12-13,00:34:00,40.701275,-73.888870,0,0,Passing or Lane Usage Improper,Unspecified,No Injury,Queens
4,4487127,2021-12-14,16:50:00,40.675884,-73.755770,0,0,Turning Improperly,Unspecified,No Injury,Queens

# Save clean data with boroughs in csvs

In [ ]:
location_df.to_csv(str(dir_path / Path('data/clean_data/location_data.csv')), index=False)

# Perform EDA on Person Data

In [20]:
person_data.head()

shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ UNIQUE_ID ┆ COLLISION ┆ CRASH_DAT ┆ CRASH_TIM ┆ … ┆ PED_ROLE  ┆ CONTRIBUT ┆ CONTRIBUT ┆ PERSON_S │
│ ---       ┆ _ID       ┆ E         ┆ E         ┆   ┆ ---       ┆ ING_FACTO ┆ ING_FACTO ┆ EX       │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ R_1       ┆ R_2       ┆ ---      │
│           ┆ i64       ┆ str       ┆ str       ┆   ┆           ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 10249006  ┆ 4229554   ┆ 10/26/201 ┆ 9:43      ┆ … ┆ Registran ┆ null      ┆ null      ┆ U        │
│           ┆           ┆ 9         ┆           ┆   ┆ t         ┆           ┆           ┆          │
│ 10255054  ┆ 4230587   ┆ 10/25/201 ┆ 15:15     ┆ … ┆ Passenger ┆ null      ┆ null      ┆ F        │
│           ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10253177  ┆ 4230550   ┆ 10/26/201 ┆ 17:55     ┆ … ┆ Registran ┆ null      ┆ null      ┆ M        │
│           ┆           ┆ 9         ┆           ┆   ┆ t         ┆           ┆           ┆          │
│ 6650180   ┆ 3565527   ┆ 11/21/201 ┆ 13:05     ┆ … ┆ Notified  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 6         ┆           ┆   ┆ Person    ┆           ┆           ┆          │
│ 10255516  ┆ 4231168   ┆ 10/25/201 ┆ 11:16     ┆ … ┆ Passenger ┆ null      ┆ null      ┆ F        │
│           ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
# Gather info about People involved in accident
person_data.describe()

shape: (9, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ statistic ┆ UNIQUE_ID ┆ COLLISION ┆ CRASH_DAT ┆ … ┆ PED_ROLE ┆ CONTRIBUT ┆ CONTRIBUT ┆ PERSON_SE │
│ ---       ┆ ---       ┆ _ID       ┆ E         ┆   ┆ ---      ┆ ING_FACTO ┆ ING_FACTO ┆ X         │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ str      ┆ R_1       ┆ R_2       ┆ ---       │
│           ┆           ┆ f64       ┆ str       ┆   ┆          ┆ ---       ┆ ---       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ str       ┆ str       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 5.49504e6 ┆ 5.49504e6 ┆ 5495040   ┆ … ┆ 5300151  ┆ 89500     ┆ 89383     ┆ 4881516   │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 194889   ┆ 5405540   ┆ 5405657   ┆ 613524    │
│ t         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ mean      ┆ 9.1385e6  ┆ 3.9693e6  ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│ std       ┆ 2.6611e6  ┆ 654793.67 ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│           ┆           ┆ 2579      ┆           ┆   ┆          ┆           ┆           ┆           │
│ min       ┆ 10922.0   ┆ 37.0      ┆ 01/01/201 ┆ … ┆ Driver   ┆ Aggressiv ┆ Accelerat ┆ F         │
│           ┆           ┆           ┆ 3         ┆   ┆          ┆ e Driving ┆ or        ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆ /Road     ┆ Defective ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆ Rage      ┆           ┆           │
│ 25%       ┆ 7.016094e ┆ 3.686295e ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│           ┆ 6         ┆ 6         ┆           ┆   ┆          ┆           ┆           ┆           │
│ 50%       ┆ 9.406377e ┆ 4.019654e ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│           ┆ 6         ┆ 6         ┆           ┆   ┆          ┆           ┆           ┆           │
│ 75%       ┆ 1.1498227 ┆ 4.369208e ┆ null      ┆ … ┆ null     ┆ null      ┆ null      ┆ null      │
│           ┆ e7        ┆ 6         ┆           ┆   ┆          ┆           ┆           ┆           │
│ max       ┆ 1.3124623 ┆ 4.762597e ┆ 12/31/202 ┆ … ┆ Witness  ┆ Windshiel ┆ View Obst ┆ U         │
│           ┆ e7        ┆ 6         ┆ 3         ┆   ┆          ┆ d Inadequ ┆ ructed/Li ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆ ate       ┆ mited     ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [22]:
# Identify which columns are null
person_data.null_count()

shape: (1, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ UNIQUE_ID ┆ COLLISION ┆ CRASH_DAT ┆ CRASH_TIM ┆ … ┆ PED_ROLE ┆ CONTRIBUT ┆ CONTRIBUT ┆ PERSON_SE │
│ ---       ┆ _ID       ┆ E         ┆ E         ┆   ┆ ---      ┆ ING_FACTO ┆ ING_FACTO ┆ X         │
│ u32       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ u32      ┆ R_1       ┆ R_2       ┆ ---       │
│           ┆ u32       ┆ u32       ┆ u32       ┆   ┆          ┆ ---       ┆ ---       ┆ u32       │
│           ┆           ┆           ┆           ┆   ┆          ┆ u32       ┆ u32       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 194889   ┆ 5405540   ┆ 5405657   ┆ 613524    │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [23]:
person_data = person_data.rename(
    {col: col.replace("_", " ") for col in person_data.columns}
)

person_data.columns

['UNIQUE ID',
 'COLLISION ID',
 'CRASH DATE',
 'CRASH TIME',
 'PERSON ID',
 'PERSON TYPE',
 'PERSON INJURY',
 'VEHICLE ID',
 'PERSON AGE',
 'EJECTION',
 'EMOTIONAL STATUS',
 'BODILY INJURY',
 'POSITION IN VEHICLE',
 'SAFETY EQUIPMENT',
 'PED LOCATION',
 'PED ACTION',
 'COMPLAINT',
 'PED ROLE',
 'CONTRIBUTING FACTOR 1',
 'CONTRIBUTING FACTOR 2',
 'PERSON SEX']

# Subsetting Data to focus on relevant columns

In [24]:

person_detail_df = person_data.select(['COLLISION ID', 'PERSON AGE', 'PERSON TYPE', 'PERSON SEX', 'BODILY INJURY', 'EJECTION'])

person_detail_df.head()

shape: (5, 6)
┌──────────────┬────────────┬─────────────┬────────────┬────────────────┬─────────────┐
│ COLLISION ID ┆ PERSON AGE ┆ PERSON TYPE ┆ PERSON SEX ┆ BODILY INJURY  ┆ EJECTION    │
│ ---          ┆ ---        ┆ ---         ┆ ---        ┆ ---            ┆ ---         │
│ i64          ┆ i64        ┆ str         ┆ str        ┆ str            ┆ str         │
╞══════════════╪════════════╪═════════════╪════════════╪════════════════╪═════════════╡
│ 4229554      ┆ null       ┆ Occupant    ┆ U          ┆ null           ┆ null        │
│ 4230587      ┆ 33         ┆ Occupant    ┆ F          ┆ Does Not Apply ┆ Not Ejected │
│ 4230550      ┆ 55         ┆ Occupant    ┆ M          ┆ null           ┆ null        │
│ 3565527      ┆ null       ┆ Occupant    ┆ null       ┆ null           ┆ null        │
│ 4231168      ┆ 7          ┆ Occupant    ┆ F          ┆ Does Not Apply ┆ Not Ejected │
└──────────────┴────────────┴─────────────┴────────────┴────────────────┴─────────────┘

In [25]:
avg_age = (
    person_detail_df
    .select(pl.col("PERSON AGE").mean())
    .item()
)
avg_age = round(avg_age)

person_detail_df = person_detail_df.with_columns(
    pl.col("PERSON AGE").fill_null(avg_age)
)

person_detail_df.head()

shape: (5, 6)
┌──────────────┬────────────┬─────────────┬────────────┬────────────────┬─────────────┐
│ COLLISION ID ┆ PERSON AGE ┆ PERSON TYPE ┆ PERSON SEX ┆ BODILY INJURY  ┆ EJECTION    │
│ ---          ┆ ---        ┆ ---         ┆ ---        ┆ ---            ┆ ---         │
│ i64          ┆ i64        ┆ str         ┆ str        ┆ str            ┆ str         │
╞══════════════╪════════════╪═════════════╪════════════╪════════════════╪═════════════╡
│ 4229554      ┆ 37         ┆ Occupant    ┆ U          ┆ null           ┆ null        │
│ 4230587      ┆ 33         ┆ Occupant    ┆ F          ┆ Does Not Apply ┆ Not Ejected │
│ 4230550      ┆ 55         ┆ Occupant    ┆ M          ┆ null           ┆ null        │
│ 3565527      ┆ 37         ┆ Occupant    ┆ null       ┆ null           ┆ null        │
│ 4231168      ┆ 7          ┆ Occupant    ┆ F          ┆ Does Not Apply ┆ Not Ejected │
└──────────────┴────────────┴─────────────┴────────────┴────────────────┴─────────────┘

In [26]:
print("Before the conversion:")
print(person_detail_df.schema)

person_detail_df = person_detail_df.with_columns(
    pl.col("PERSON AGE").cast(pl.Int32)
)

print("After the conversion:")
print(person_detail_df.schema)

person_detail_df.head()

Before the conversion:
Schema({'COLLISION ID': Int64, 'PERSON AGE': Int64, 'PERSON TYPE': String, 'PERSON SEX': String, 'BODILY INJURY': String, 'EJECTION': String})
After the conversion:
Schema({'COLLISION ID': Int64, 'PERSON AGE': Int32, 'PERSON TYPE': String, 'PERSON SEX': String, 'BODILY INJURY': String, 'EJECTION': String})

shape: (5, 6)
┌──────────────┬────────────┬─────────────┬────────────┬────────────────┬─────────────┐
│ COLLISION ID ┆ PERSON AGE ┆ PERSON TYPE ┆ PERSON SEX ┆ BODILY INJURY  ┆ EJECTION    │
│ ---          ┆ ---        ┆ ---         ┆ ---        ┆ ---            ┆ ---         │
│ i64          ┆ i32        ┆ str         ┆ str        ┆ str            ┆ str         │
╞══════════════╪════════════╪═════════════╪════════════╪════════════════╪═════════════╡
│ 4229554      ┆ 37         ┆ Occupant    ┆ U          ┆ null           ┆ null        │
│ 4230587      ┆ 33         ┆ Occupant    ┆ F          ┆ Does Not Apply ┆ Not Ejected │
│ 4230550      ┆ 55         ┆ Occupant    ┆ M          ┆ null           ┆ null        │
│ 3565527      ┆ 37         ┆ Occupant    ┆ null       ┆ null           ┆ null        │
│ 4231168      ┆ 7          ┆ Occupant    ┆ F          ┆ Does Not Apply ┆ Not Ejected │
└──────────────┴────────────┴─────────────┴────────────┴────────────────┴─────────────┘

In [27]:
# Change the Person Sex Column
person_detail_df = person_detail_df.with_columns(
    pl.col("PERSON SEX")
      .replace({
          "M": "Male",
          "F": "Female",
          "U": "Unknown",
      })
      .fill_null("UNKNOWN")
)

print(
    person_detail_df
    .select(pl.col("PERSON SEX").value_counts())
)

shape: (4, 1)
┌────────────────────┐
│ PERSON SEX         │
│ ---                │
│ struct[2]          │
╞════════════════════╡
│ {"Female",1486701} │
│ {"UNKNOWN",613524} │
│ {"Unknown",432574} │
│ {"Male",2962241}   │
└────────────────────┘

In [28]:
# Drop the columns where the bodily injury is not described
person_detail_df = person_detail_df.filter(
    pl.col("BODILY INJURY") != "Unknown"
)

person_detail_df.select(
    pl.col("BODILY INJURY").value_counts()
)

shape: (13, 1)
┌────────────────────────────────┐
│ BODILY INJURY                  │
│ ---                            │
│ struct[2]                      │
╞════════════════════════════════╡
│ {"Eye",916}                    │
│ {"Face",12956}                 │
│ {"Neck",77278}                 │
│ {"Back",80437}                 │
│ {"Does Not Apply",2425278}     │
│ …                              │
│ {"Shoulder - Upper Arm",33130} │
│ {"Chest",17564}                │
│ {"Entire Body",39435}          │
│ {"Knee-Lower Leg Foot",74045}  │
│ {"Elbow-Lower-Arm-Hand",33220} │
└────────────────────────────────┘

In [29]:
person_detail_df.columns

['COLLISION ID',
 'PERSON AGE',
 'PERSON TYPE',
 'PERSON SEX',
 'BODILY INJURY',
 'EJECTION']

Create a super dataframe with Location and Additional Person data

In [30]:
# Replace spaces with underscores in all column names
location_df = pl.from_pandas(location_df)
merge_df = location_df.join(
    person_detail_df,
    on="COLLISION ID",
    how="inner"
)

print("Location DF shape:", location_df.shape)
print("Person DF shape:", person_detail_df.shape)
print("Merged DF shape:", merge_df.shape)

merge_df.head(10)

Location DF shape: (1079129, 11)
Person DF shape: (2886627, 6)
Merged DF shape: (1860340, 16)

shape: (10, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ COLLISION ┆ CRASH     ┆ CRASH     ┆ LATITUDE  ┆ … ┆ PERSON    ┆ PERSON    ┆ BODILY    ┆ EJECTION │
│ ID        ┆ DATE      ┆ TIME      ┆ ---       ┆   ┆ TYPE      ┆ SEX       ┆ INJURY    ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ i64       ┆ datetime[ ┆ time      ┆           ┆   ┆ str       ┆ str       ┆ str       ┆          │
│           ┆ ms]       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4230587   ┆ 2019-10-2 ┆ 15:15:00  ┆ 40.703957 ┆ … ┆ Occupant  ┆ Female    ┆ Does Not  ┆ Not      │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆ Apply     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230743   ┆ 2019-10-2 ┆ 19:15:00  ┆ 40.695847 ┆ … ┆ Occupant  ┆ Male      ┆ Back      ┆ Not      │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230737   ┆ 2019-10-2 ┆ 00:41:00  ┆ 40.69731  ┆ … ┆ Occupant  ┆ Male      ┆ Does Not  ┆ Not      │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ Apply     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230715   ┆ 2019-10-2 ┆ 08:50:00  ┆ 40.75884  ┆ … ┆ Bicyclist ┆ Male      ┆ Knee-Lowe ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ r Leg     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆ Foot      ┆          │
│ 4230926   ┆ 2019-10-2 ┆ 23:29:00  ┆ 40.714928 ┆ … ┆ Occupant  ┆ Male      ┆ Does Not  ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ Apply     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230733   ┆ 2019-10-1 ┆ 19:45:00  ┆ 40.696648 ┆ … ┆ Occupant  ┆ Male      ┆ Does Not  ┆ Not      │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ Apply     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4229616   ┆ 2019-10-2 ┆ 15:40:00  ┆ 40.74478  ┆ … ┆ Occupant  ┆ Male      ┆ Does Not  ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ Apply     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4229773   ┆ 2019-10-2 ┆ 16:50:00  ┆ 40.75667  ┆ … ┆ Occupant  ┆ Female    ┆ Head      ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230652   ┆ 2019-10-2 ┆ 12:45:00  ┆ 40.610676 ┆ … ┆ Occupant  ┆ Female    ┆ Does Not  ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ Apply     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230907   ┆ 2019-10-2 ┆ 11:00:00  ┆ 40.787563 ┆ … ┆ Occupant  ┆ Female    ┆ Does Not  ┆ Not      │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆ Apply     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:

# Fill nulls for specific columns
merge_df = merge_df.with_columns([
    pl.col("EJECTION").fill_null("Unknown"),
    pl.col("BODILY INJURY").fill_null("Unknown"),
    pl.col("PERSON AGE").fill_null(0),
    pl.col("PERSON TYPE").fill_null("Unknown"),
    pl.col("PERSON SEX").fill_null("Unknown"),
])

# Replace 'Does Not Apply' with 'Unknown' in string columns
string_cols = ["EJECTION", "BODILY INJURY", "PERSON TYPE", "PERSON SEX"]
merge_df = merge_df.with_columns([
    pl.when(pl.col(c) == "Does Not Apply")
      .then(pl.lit("Unknown"))
      .otherwise(pl.col(c))
      .alias(c)
    for c in string_cols
])

In [32]:
merge_df.head(20)

shape: (20, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ COLLISION ┆ CRASH     ┆ CRASH     ┆ LATITUDE  ┆ … ┆ PERSON    ┆ PERSON    ┆ BODILY    ┆ EJECTION │
│ ID        ┆ DATE      ┆ TIME      ┆ ---       ┆   ┆ TYPE      ┆ SEX       ┆ INJURY    ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ i64       ┆ datetime[ ┆ time      ┆           ┆   ┆ str       ┆ str       ┆ str       ┆          │
│           ┆ ms]       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4230587   ┆ 2019-10-2 ┆ 15:15:00  ┆ 40.703957 ┆ … ┆ Occupant  ┆ Female    ┆ Unknown   ┆ Not      │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230743   ┆ 2019-10-2 ┆ 19:15:00  ┆ 40.695847 ┆ … ┆ Occupant  ┆ Male      ┆ Back      ┆ Not      │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230737   ┆ 2019-10-2 ┆ 00:41:00  ┆ 40.69731  ┆ … ┆ Occupant  ┆ Male      ┆ Unknown   ┆ Not      │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230715   ┆ 2019-10-2 ┆ 08:50:00  ┆ 40.75884  ┆ … ┆ Bicyclist ┆ Male      ┆ Knee-Lowe ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ r Leg     ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆ Foot      ┆          │
│ 4230926   ┆ 2019-10-2 ┆ 23:29:00  ┆ 40.714928 ┆ … ┆ Occupant  ┆ Male      ┆ Unknown   ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 4322803   ┆ 2020-06-2 ┆ 12:06:00  ┆ 40.668648 ┆ … ┆ Occupant  ┆ Male      ┆ Head      ┆ Not      │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4229612   ┆ 2019-10-2 ┆ 12:06:00  ┆ 40.693985 ┆ … ┆ Occupant  ┆ Female    ┆ Unknown   ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230709   ┆ 2019-10-2 ┆ 05:03:00  ┆ 40.764828 ┆ … ┆ Occupant  ┆ Male      ┆ Unknown   ┆ Not      │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4230439   ┆ 2019-10-2 ┆ 00:05:00  ┆ 40.769115 ┆ … ┆ Bicyclist ┆ Male      ┆ Elbow-Low ┆ Ejected  │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆ er-Arm-Ha ┆          │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆ nd        ┆          │
│ 4230398   ┆ 2019-10-2 ┆ 20:00:00  ┆ 40.793377 ┆ … ┆ Occupant  ┆ Male      ┆ Unknown   ┆ Not      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ejected  │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# Save to a csv file
person_detail_df.to_pandas().to_csv(str(dir_path / Path('data/clean_data/person_detail.csv')), index=False)

In [ ]:
# Save to a csv file
merge_df.to_pandas().to_csv(str(dir_path / Path('data/clean_data/merged_data.csv')), index=False)